### ISSUE TITLE
pip install on Ubuntu 16.04 results in non-executable cytherize.py

### ISSUE THREAD

**Issue by mbdevpl** [nickpandolfi/Cyther#1]
Hello,

I've decided to try out the Cyther module today, and it seems that there is an error in `setup.py`, because the cytherize script is not executable, so I cannot easily execute it.

```
$ ls -lah ~/.local/bin/cytherize.py 
-rw-rw-r-- ...
$ which cytherize.py
(nothing)
```

Also, please consider using `entry_points` argument of setuptools instead of `scripts` in setup.py (https://github.com/nickpandolfi/Cyther/blob/master/setup.py#L44), it makes life easier and you can get rid of ".py" extension from the exectuable script.

BTW, implementing `__main__.py` would result in a user being able to do: `python3.5 -m cyther [args]` which is a standard practice for packages that have a CLI: https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/

**Comment by nickpandolfi** [comment]
Thanks for the suggestion. Currently looking into the two issues you posted.

**Comment by marcgardiner** [comment]
Thanks for the blog, in my case it cause of the version of python.
